### ISSUE TITLE
Incompatible with Kotlin's DSL

### ISSUE THREAD

**Issue by groov1kk** [Nordstrom/JUnit-Foundation#40]
As Kotlin provides to use [multi-word method names](https://kotlinlang.org/docs/reference/coding-conventions.html#names-for-test-methods), it is make incompatible to use this library with Kotlin's tests which use such methods.

There is an explicit splitting of test names inside of AtomicTest class constructor.  Providing multi-word method name, this constructor takes only the first word of this method's name and tries to find this name in given particles. Of course it will find nothing. 

**Steps to reproduce:**

1. Create Kotlin class.
2. Create test method using multi-words syntax (for example _fun 'some method'() {...}_)
3. Integrate it with JUnit-Foundation and run test

**Expected behavior:**

AtomicTest class constructor initializes identity field with created method.

**Actual behavior:**

AtomicTest class constructor does not initializes identity field.

**Comment by sbabcoc** [comment]
This issue is resolved by https://github.com/Nordstrom/JUnit-Foundation/pull/41
