### ISSUE TITLE
Uncomfortable way to initialize listeners, watchers etc.

### ISSUE THREAD

**Issue by brutskov** [Nordstrom/JUnit-Foundation#61]
You are using service loader to load customer listeners and watchers by component (one listener - one service file).  It makes sense to create some marker interface (like LifecycleItem) and load all listeners and watchers on one ServiceLoader call. You'l resolve and collect our listeners by type on your side but users will be have only one META-INF/services/LifecycleItem file in the classpath.

![image](https://user-images.githubusercontent.com/20353034/77571857-13f7f100-6edf-11ea-805a-31ef66167eb5.png)

**Comment by sbabcoc** [comment]
Good suggestion. I'll see about rolling that out soon.

**Comment by brutskov** [comment]
@sbabcoc , thank you!

**Comment by sbabcoc** [comment]
I have a pull request that implements the revised watcher attachment strategy.
https://github.com/Nordstrom/JUnit-Foundation/pull/63
As implemented, this is a breaking change. I could continue to support the previous approach in parallel, but this greatly complicates the implementation. My preference is to publish this as a major-version update and require clients to consolidate their SPI configuration files.
